<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EventManipulation.aspx.cs" Inherits="OnlineEventManagementSystem.Website.EventManipulation" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView runat="server" ID="gvEvent" AutoGenerateColumns="false" DataKeyNames="EventID" ShowFooter="true" ShowHeaderWhenEmpty="true" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowCancelingEdit="gvEvent_RowCancelingEdit" OnRowDeleting="gvEvent_RowDeleting" OnRowEditing="gvEvent_RowEditing" CellSpacing="4" AlternatingRowStyle-HorizontalAlign="Center" OnSelectedIndexChanged="gvEvent_SelectedIndexChanged">
                <Columns>
                    <asp:TemplateField HeaderText="Event ID">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtEventID" runat="server" Text='<%# Bind("EventID") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblEventID" runat="server" Text='<%# Bind("EventID") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="txtEventID" runat="server"></asp:TextBox>
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Event Name">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtEventName" runat="server" Text='<%# Bind("EventName") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblEventName" runat="server" Text='<%# Bind("EventName") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="txtEventName" runat="server"></asp:TextBox>
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Event Type">
                        <EditItemTemplate>
                            <asp:RadioButtonList ID="rbEventType" runat="server" DataValueField='<%# Bind("EventType") %>'>
                                <asp:ListItem>Personal</asp:ListItem>
                                <asp:ListItem>Corporate</asp:ListItem>
                            </asp:RadioButtonList>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="rbEventType" runat="server" Text='<%# Bind("EventType")%>' ></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:RadioButtonList ID="rbEventType" runat="server" DataValueField='<%# Bind("EventType") %>'>
                                <asp:ListItem>Personal</asp:ListItem>
                                <asp:ListItem>Corporate</asp:ListItem>
                            </asp:RadioButtonList>
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField>
                        <FooterTemplate>
                            <asp:Button runat="server" Text="Insert" OnClick="InsertEvent" />
                        </FooterTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
